
// // Utilities List // //

// List -> Commas [✔️]

// Word Count [✔️]

// Random string generator [✔️]

// IPV4 validator/generator [✔️]

// Random SIN generator [✔️]

// SIN validator [✔️]

// Random hex color generator [✔️]

// Google Search [✔️]

// Time Zone converter + detectors [✔️]

// Remove Duplicates From CSV/New line SV list (e.g. used for Spotify) [✔️]

// Dark Mode on UI [✔️]

// Convert text generated by buttons/actions to dark mode too so it is the right color when dark mode is on [✔️]

// Text below "generate random sin" - the sin [✔️]

// Make by default, dark mode instead of light mode [✔️]

// Fix broken wiki link for timezones info [✔️]

// Remove alerts, change to HTML/CSS; alerts are annoying and not the most user friendly [✔️]

// Clean up UI/make small improvements/enhancements before pushing (e.g. put hex color code in color box) [✔️]

// Add Contact info / more about you at the bottom of the extension (like on Serenity application)

// Maybe fix vTools failed to load source map: Could not load content for chrome-extension://mobofkhebjfbhfidipgacfiamoplighl/scripts/moment-with-locales.min.js.map: System error: net::ERR_FILE_NOT_FOUND error in console


// Hard To Do/Will Take More Thinking/Time/Etc.:

// Random font picker 

// Unit Converter 

// IPV6 validator/generator 

// Weather 

// Part 2: Remove alerts, change to HTML/CSS; alerts are annoying and not the most user friendly - is this even needed? What should the alerts be replaced with? Should alerts and text output BOTH be kept? "Copied" message? Investigate.


// Triggers when all DOM elements are loaded
document.addEventListener('DOMContentLoaded', function(event) 
{
	turnDarkModeOnByDefault();
	initTimezoneData();

	document.querySelector('#darkModeToggle').addEventListener('click', function (event2)
	{
		toggleDarkMode();	
	});

	document.querySelector('#fromInputTimezone').addEventListener('input', async function(event2) 
	{
		let childNodes = document.querySelector('#fromTimezones').childNodes;
		let from = validateAndGetInput("fromInputTimezone", "Please ensure a valid from timezone is selected.", false);
		let fromInputTzAbb = document.querySelector("#fromTZAbb");
		let tzAbbSet = false;
		
		// let toInputTzAbb = document.querySelector("#toTZAbb");

		for (let i = 0; i<childNodes.length; i++)
		{
			if (from === childNodes[i].value)
			{
				tzAbbSet = true;
				fromInputTzAbb.innerHTML = getAbbFromTimezone(moment.tz(moment(), from));
			}
		}

		if (!tzAbbSet)
		{
			fromInputTzAbb.innerHTML = "";					
		}	
	});

	document.querySelector('#toInputTimezone').addEventListener('input', async function(event2) 
	{
		let childNodes = document.querySelector('#toTimezones').childNodes;
		let from = validateAndGetInput("toInputTimezone", "Please ensure a valid from timezone is selected.", false);
		let toInputTzAbb = document.querySelector("#toTZAbb");
		let tzAbbSet = false;
		
		// let toInputTzAbb = document.querySelector("#toTZAbb");

		for (let i = 0; i<childNodes.length; i++)
		{
			if (from === childNodes[i].value)
			{
				tzAbbSet = true;
				toInputTzAbb.innerHTML = getAbbFromTimezone(moment.tz(moment(), from));
			}
		}		

		if (!tzAbbSet)
		{
			toInputTzAbb.innerHTML = "";					
		}
	});

	document.querySelector('#convertTZ').addEventListener('click', async function(event2) 
  {
  	let from = validateAndGetInput("fromInputTimezone", "Please ensure a valid from timezone is selected.");
  	let to = validateAndGetInput("toInputTimezone", "Please ensure a valid to timezone is selected.");
  	let time = validateAndGetInput("inputDateTime", "Please ensure a valid to timezone is selected.");
  	let convertedTime = convertTimeZones(from, to, time);
  	let output = displayDateTime(convertedTime, to);
  	console.log(convertedTime, output);
  	document.querySelector('#timezoneOutput').innerHTML = output;
  });

	document.querySelector('#listToCommas').addEventListener('click', async function(event2) 
  {
  	let list = validateAndGetInput("listInput", "Please enter a space or newline (or both) separated list to continue.");
  	if (list != null)
  	{
  		await convert(list);
  	}
  });

	document.querySelector('#removeDuplicates').addEventListener('click', async function(event2) 
  {
  	let list = validateAndGetInput("removeDuplicatesInput", "Please enter a space or newline (or both) separated list to continue.");
  	if (list != null)
  	{
  		await removeDuplicates(list);
  	}
  });

   document.querySelector('#genRandomStr').addEventListener('click', async function(event2) 
   {
  	let desiredLength = document.querySelector('#desiredLenInput').value;
  	if ((!desiredLength == "" || !desiredLength == null) && (isNaN(desiredLength) || +desiredLength <= 0))
  	{
  		console.error('Error message to display...');
  		alert("Please specify a valid length or simply leave it blank (default length is 20).");
  		return;
  	}

  	// console.log(desiredLength);
  	let formElems = document.querySelector("#genRandomStrForm").children;
  	let exclusions = 
  	{
  		upperLetters: false, 
  		lowerLetters: false, 
	  	numbers: false, 
	  	symbols: false
  	};

  	if (formElems != null)
  	{
  		exclusions.upperLetters = formElems.upperLetters.checked;
  		exclusions.lowerLetters = formElems.lowerLetters.checked;
  		exclusions.symbols = formElems.symbols.checked;
  		exclusions.numbers = formElems.numbers.checked;

  		if (exclusions.upperLetters && exclusions.symbols && exclusions.numbers && exclusions.lowerLetters)
  		{
  			console.error('Error message to display...');
  			alert("Please leave at least one of the above checkboxes unchecked.")
  			return;
  		}
  	}

  	else 
  	{
  		console.error("Failed to get random str form, assuming no exclusions but error.");	
  	}

  	const generatedStr = 
  	(desiredLength == "" || desiredLength == null ? generateRandomString(exclusions) : generateRandomString(exclusions, desiredLength));

   	copyAndNotify(generatedStr, "Random string generated and copied:\n\n" + generatedStr);
   });

  document.querySelector('#validateSIN').addEventListener('click', function(event2) 
  {
  	let SIN = validateAndGetInput("SINInput", "Please enter a SIN to continue.");
  	if (SIN != null)
  	{
  		let sinValidationOutput = "SIN is " + (isValidSIN(SIN) ? "valid" : "invalid") + ".";
  		alert(sinValidationOutput);
  		console.log(isValidSIN(SIN));
  	}
  });

  document.querySelector('#generateRandomSIN').addEventListener('click', async function(event2) 
  {
  	let SIN = randomSINGeneratorV2();
  	copyAndNotify(SIN, "Random SIN generated and copied! SIN: " + SIN);
  	let outputDiv = document.querySelector('#randomSINOutput');
	  outputDiv.innerHTML = SIN;
  });

   document.querySelector('#generateRandomColor').addEventListener('click', async function(event2) 
  {
  	const hexCode = generateRandomHexCode();
  	let randomColorDiv = document.querySelector('#randomColor');
  	let randomColorTextDiv = document.querySelector('#randomColorText');
  	randomColorDiv.style.backgroundColor = hexCode;
  	randomColorDiv.style.height = "3em";
  	randomColorTextDiv.innerHTML = hexCode;
  	await copyAndNotify(hexCode, "Random colour's hex code generated and copied! Code: " + hexCode);
  });

  document.querySelector('#validateIPV4').addEventListener('click', function(event2) 
  {
  	let input = validateAndGetInput("IPV4Input", "Please enter an input to continue.");
  	if (input != null)
  	{
	  	let validity = isIPV4Valid(input);
	  	let IPV4ValidationOutput = "IP address is " + (validity ? "valid" : "invalid") + ".";
	  	alert(IPV4ValidationOutput);
	  	console.log(validity);	
  	}
  });   

  document.querySelector('#wordCount').addEventListener('click', function(event2) 
  {	
  	let input = validateAndGetInput("wordsInput", "Please enter an input to continue.");
  	let exclusionMaxLen = document.querySelector('#wordLenExclusion').value;
  	exclusionMaxLen = exclusionMaxLen == null || exclusionMaxLen == "" ? 0 : exclusionMaxLen;
  	if (input != null)
  	{
  		let wordCount = countWords(input, exclusionMaxLen);
	  	console.log(wordCount);
	  	let wordCountOutput = "Input is " + wordCount + " words long."
	  	alert(wordCountOutput);
	  	let outputDiv = document.querySelector('#wordCountOutput');
	  	outputDiv.innerHTML = wordCountOutput;
  	}
  });

  document.querySelector('#search').addEventListener('click', async function(event2)
  {
  	let input = validateAndGetInput("searchInput", "Please enter an input to continue.");
  	if (input != null)
  	{
  		await searchInternet(input);
  	}
  });
});

const toggleDarkMode = () =>
{
	// get all relevant classes here, and dynamically turn them black/white

	console.log('Dark mode toggled...');
	const body = document.body;
	const isDarkModeOn = body.classList.toggle("dark_mode_bg");
	const relevantClasses = ["darkModeText"];

	for (let relClass of relevantClasses)
	{
		console.log(relClass);
		console.log(isDarkModeOn);
		let foundClasses = document.querySelectorAll("."+relClass);
		console.log(foundClasses);
		for (foundClass of foundClasses)
		{
			// turn everything needed black/white (e.g. text)
			foundClass.style.color = isDarkModeOn ? "rgba(255, 255, 255, 1)" : "rgba(0, 0, 0, 1)";
		}
	}
}

const copyAndNotify = async (output, outputMsg) => 
{
	console.log(output);
	await navigator.clipboard.writeText(output);
	alert(outputMsg);
}

const convert = async (list) => 
{	
	console.log(list);
	// future TODO maybe: if multiple spaces/newlines in a row, don't separate by comma, just ignore those until another charcter type is matched

	let output = "";
	let counter = 1;

	for (char of list.trim())
	{
		if (char !== "\n" && char !== " ")
		{
			output+=char;
		}

		else
		{
			counter+=1;
			output+=", ";
		}
	}

	console.log(counter + " # of items in final list.")
	await copyAndNotify(output, "Copied!");
	return;
}

const generateRandomString = (exclusions, desiredLength = 20, levelOfRandomness = 10) =>
{	
	/*
	// levelOfRandomness should be on a scale from 1 to 10 for speed-randomness balanceness
	// Big-O time: 
	// n here is 94, as that's the length of randomCharPool.
	// shuffleArr is O(n).
	// Array.from is O(n) as well
	// The for loop in step 3 is O(desiredLength).
	// Since the for loop in step 2 is O(1000*levelOfRandomness), the total Big(O) of this algorithm is:
	// Big(O) = O(n) + O(1000*levelOfRandomness*n) + O(desiredLength)
	// O(1000*levelOfRandomness*n) is the biggest level of magnitude here. 
	// For default levelOfRandomness 10, therefore the big O is O(1000*10*n) or O(10000n) or O(n).

	// Speed example: levelOfRandomness = 10 is 10000 iterations in step 3, which takes about 20 milliseconds.
	// levelOfRandomness = 10 gives a very high level of randomness, with a neglible runtime
	*/

	// randomCharPool is generated in Python using 2 lines of code:

	/* 
		import string
		print(string.ascii_letters + string.digits + string.punctuation)-
	*/ 

	// This yields this string:
	// abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~


	console.time("generateRandomString");

	// Step 1: get randomCharPool based on exclusions
	let randomCharPool = "";
	if (!exclusions.upperLetters)
	{
		randomCharPool+="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	}

	if (!exclusions.lowerLetters)
	{
		randomCharPool+="abcdefghijklmnopqrstuvwxyz";
	}

	if (!exclusions.symbols)
	{
		randomCharPool+="!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";
	}

	if (!exclusions.numbers)
	{
		randomCharPool+="0123456789";
	}

	let randomCharArr = Array.from(randomCharPool);
	let output = "";

	// Step 2: shuffle random characters i amount of times to ensure randomness
	for (let i = 0; i<(1000*levelOfRandomness); i++)
	{
		randomCharArr = shuffleArr(randomCharArr);
	}

	const randomizedStr = randomCharArr.join('');
	console.log(randomizedStr);

	// Step 3: randomly pick out characters until the desired string length is met
	for (let i = 0; i<desiredLength; i++)
	{
		output+=randomizedStr[getRandomInteger(randomizedStr.length-1)];
	}

	console.timeEnd("generateRandomString");

	console.log(desiredLength, levelOfRandomness, output);
	return output;
}

const getRandomInteger = (max, min = 0) => 
{
	// gets random integer from min to max, inclusive - that is [min, max], mathematically written
  	return Math.floor(Math.random() * (max - min + 1)) + min;
}

const shuffleArr = (arr) =>
{
  // understand algorithm fully
  for (let i = arr.length - 1; i > 0; i--) 
  {
  	const j = getRandomInteger(i);
    // console.log(i, j);
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }

  // console.log(arr);
  return arr;
}

const isValidSIN = (input) =>
{
	let num = String(input);
	console.log(num, input);
	if (input == null || isNaN(num) || num.length != 9)
	{
		return false;
	}

	let productStr = "";
	let productSum = 0;
	for (let i = 0; i<num.length; i++)
	{
		if (i % 2 == 0)
		{
			productStr+=num[i];	
		}
		
		else
		{
			productStr+=num[i]*2;
		} 
	}

	console.log(productStr);
	for (let digit of productStr)
	{
		productSum+=+digit;
	}

	console.log(productSum);
	return (productSum % 10 == 0);
}

const randomSINGenerator = () => 
{
	// random sin generator method 1
	// generate a random digit for each digit, combine digits to generate the random integer
	// per digit method
	let SinStr = "";
	let counter = 0;
	while (!isValidSIN(SinStr))
	{
		counter++;
		for (let i = 0; i<9; i++)
		{
			SinStr+=getRandomInteger(9);
		}
	}

	console.log('Random Sin Generator took ' + counter + ' number of times to generate a random SIN');
	return SinStr;
}

const randomSINGeneratorV2 = () => 
{
	// currently using this method as mathematically, as method 1 is way too inefficient and slow because of the nested for loop
	// this method also ensures random SINs, but more efficiently

	// random sin generator method 2
	// use the minimum and maximum mathematically possible 9 digit numbers to generate the random integer
	// per number method
	let SINNum = 0;
	let counter = 0;
	while (!isValidSIN(SINNum))
	{
		counter++;
		SINNum = getRandomInteger(999999999, 100000000);
	}

	console.log('Random Sin Generator V2 took ' + counter + ' number of times to generate a random SIN');
	return SINNum;
}

const generateRandomHexCode = () => 
{	
	let randomCode = "#";
	for (let i = 0; i<6; i++)
	{
		randomCode+=getRandomInteger(15).toString(16);
	}

	console.log(randomCode);
	return randomCode;
}

const isIPV4Valid = (address) => 
{
	if (address == null || address == "")
	{
		return false;
	}

	const parts = String(address).split(".");

	if (parts.length !== 4)
	{
		return false;
	}

	for (let part of parts)
	{
		// 8 bits max per part
		if (part == null || isNaN(part) || +part < 0 || +part > 255)
		{
			return false;
		}
	}

	return true;
}

const countWords = (words, exclusionMaxLen = 0) =>
{
	// possible TODO: return # of characters too from this function, and display

	// split words by whitespace
	let wordsArr = words.split(/\s+/);

	// possible TODO: decide if this is needed or not; if it is, use it (probably not needed on my current conclusion)
	// remove punctuation
	let allPunctuation = "!\"#$%&'()*+, -./:;<=>?@[\]^_`{|}~"; // reference

	console.log(wordsArr);
	return (wordsArr.filter(word => word.length > exclusionMaxLen)).length;
}

const searchInternet = async (input) => 
{
	// uses Google search engine
	window.open("http://google.com/search?q=" + input);
}

const validateAndGetInput = (inputId, errMsg, alertUserOnMissingData = true) =>
{
	let input = document.querySelector("#" + inputId).value;
	console.log(input);
	if (alertUserOnMissingData && (input == null || input == ""))
	{
  	alert(errMsg);
  	return;
  }

  return input;
}

const removeDuplicates = async (input) =>
{
	// future TODO maybe: if multiple spaces/newlines in a row, don't count it as an element,
	// just ignore it until another charcter type is matched

	// useful for many things
	// e.g. for removing duplicates from Spotify

	let output = "";
	input = input.replaceAll(" ", "\n"); // convert every space separated entry to new line separated entry
	let inputArr = input.split("\n");
	let outputArr = Array.from(new Set(inputArr));
	outputArr.forEach(line => output+=line+="\n");
	inputArr.length
	console.log(output);
	console.log("Input: " , inputArr.length, "\nOutput: ", outputArr.length);
	let inputListOutput = "The input has " + inputArr.length + " " + (inputArr.length === 1 ? "item." : "items.");
	let outputListOutput = "The output has " + outputArr.length + " " + (outputArr.length === 1 ? "item." : "items.");

	await copyAndNotify(output, "Copied!");
	let outputListDiv = document.querySelector('#outputListLength');
	outputListDiv.innerHTML = outputListOutput;
	let inputListDiv = document.querySelector('#inputListLength');
	inputListDiv.innerHTML = inputListOutput;
	let endOfSectionBr = document.querySelector('#endOfRemoveDuplicatesBr');
	endOfSectionBr.style.display = "initial";
	return;
}

const isIPV6Valid = (address) => 
{
	// TODO: code here

	return false;
}


const initTimezoneData = () =>
{	
	// init neccesary variables
	const userTimezone = getUserTimezone();

	// hack to always get UTC (GMT) time as default "to" timezone, as "Europe/London" in timezones variable sadly follows DST, so in the summer
	// it is GMT + 1 (BST - British Summer Time). Source:
	// https://www.google.com/search?q=does+america%2Fdanmarkshavn+have+daylight+savings+time&rlz=1C1CHBF_enCA777CA777&sxsrf=APwXEdf4XFO9ybDshfLdJHx_s-PQPHR6xg%3A1683609612363&ei=DNhZZK_qFbeE0PEPqOKGwAs&oq=does+America%2FDanmarkshavn++have+daylig&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAxgAMgcIIRCgARAKMgcIIRCgARAKMgcIIRCgARAKMgQIIRAVOgQIIxAnOgUIABCABDoHCAAQHhCLAzoHCCMQsAIQJzoHCAAQDRCABDoJCAAQHhANEIsDOggIIRCgARDDBDoFCCEQoAE6BAghEApKBAhBGABQAFi2FmChHGgAcAF4AIABbogBsg2SAQQxNy4zmAEAoAEBuAECwAEB&sclient=gws-wiz-serp
	const utcTimezone = "America/Danmarkshavn"; 
	const timezones = getAllTimeZones();
	let listElements = [];
	let fromInputTzBox = document.querySelector("#fromInputTimezone");
	let toInputTzBox = document.querySelector("#toInputTimezone");
	let fromInputTzAbb = document.querySelector("#fromTZAbb");
	let toInputTzAbb = document.querySelector("#toTZAbb");

	listElements.push(document.querySelector('#fromTimezones'));
	listElements.push(document.querySelector('#toTimezones'));

	// set user's default time zone
	document.querySelector("#userTimezone").innerHTML = userTimezone;

	// set dault datetime
	setDefaultInputDatetime();
	let testingOutput = "";

	// set up timezone dropdowns, with default options
	for (let element of listElements)
	{
		for (let timezone of timezones)
		{
			let newOption = document.createElement("option");
			newOption.textContent = timezone;
			newOption.value = timezone;
			element.appendChild(newOption);

			if (timezone === userTimezone)
			{
				fromInputTzBox.value = timezone;
				fromInputTzAbb.innerHTML = getAbbFromTimezone(moment.tz(moment(), timezone));
			}

			if (timezone === utcTimezone)
			{
				toInputTzBox.value = timezone;
				toInputTzAbb.innerHTML = getAbbFromTimezone(moment.tz(moment(), timezone));
			}

			testingOutput+=getAbbFromTimezone(moment.tz(moment(), timezone))+" " + timezone+"\n"; 
		}
	}
	
	// console.log(testingOutput);

}

const setDefaultInputDatetime = () =>
{
	// set user datetime to current user datetime
	// we want the first 17 characters from moment().format():
	// moment().format() string: "2023-02-04T00:45:56-07:00" 
	// target string: "2023-02-04T01:42"
	const userTimezoneElem = document.querySelector("#inputDateTime");
	userTimezoneElem.value = moment().format().slice(0, 16);
}

// timezone and date time helper functions

const convertTimeZones = (from, to, dateTime) =>
{
	// use moment-t zto convert timezones and format times from from timezone  to timezone easily
	console.log(from, to, dateTime);

	// todo replace .format() string to something more readable
	let fromDT = moment.tz(dateTime, from);
	let toDT = fromDT.clone().tz(to); // use .format() and use a string to format as you want
	console.log(fromDT.format(), toDT.format());

	return toDT;
}

const displayDateTime = (dateTime, to) => 
{
	console.log(dateTime);
	let offset = getUTCOffsetFromMomentDTInHours(dateTime);
	let abb = getAbbFromTimezone(dateTime, true);
	let spaceNeeded = abb !== "";
	let outputStr = "It is " + dateTime.format("MMMM Do, YYYY h:mm A") + (spaceNeeded ? " " : "") +
	getAbbFromTimezone(dateTime, true) + " in " + to;
	outputStr += getUTCOffsetString(offset);
	return outputStr;
}

const getUTCOffsetString = (offset) =>
{	
	let baseEndStr = " UTC/GMT time).";

	if (offset === 0)
	{
		return " (the same as" + baseEndStr;
	}

	return " (" + offset + " hours " + (offset < 0 ? "behind" : "ahead of") + baseEndStr;
}

const getUTCOffsetFromMomentDTInHours = (dateTime) =>
{
	return (dateTime.utcOffset())/60;
}


const getUserTimezone = () => 
{
	// returns string
	return Intl.DateTimeFormat().resolvedOptions().timeZone;
}

const getAllTimeZones = () => 
{
	// returns array of strings
	return Intl.supportedValuesOf('timeZone');
}

const getUserLocalTimezoneAbb = () =>
{
  return new Date().toLocaleTimeString('en-us', {timeZoneName:'short'}).split(' ')[2];
}

const getAbbFromTimezone = (time, onlyShowStringAbb = false) =>
{
	// time should be moment type
	let abb = time.zoneAbbr();
	return onlyShowStringAbb ? (isNaN(abb) ? abb : "") : abb;
}

const formatDateTimeForLocalTimezone = (dateTime) =>
{
  if (dateTime == null)
  {
    return "";
  }

  return dateTime.tz(this.getUserLocalTimeZone()).format("MMMM Do, YYYY h:mm A") 
  + " " + this.getUserLocalTimezoneAbb();
}

const turnDarkModeOnByDefault = () =>
{
	let darkModeToggle = document.querySelector("#darkModeToggle");
	darkModeToggle.checked = true;
	toggleDarkMode();
}